name: ci

on:
   push:
      branches:
         - backer
         - patron

permissions:
   contents: write

jobs:
   deploy:
      runs-on: ubuntu-latest
      steps:
         - name: Check out the code
           uses: actions/checkout@v3

         - name: Set up Python
           uses: actions/setup-python@v4
           with:
              python-version: 3.x

         - name: Install dependencies
           run: |
              pip install mkdocs-material mike mkdocs-roamlinks-plugin

         - name: Deploy documentation
           env:
              VERSION_NAME: ${{ github.ref_name }}
           run: |
              if [ "$VERSION_NAME" = "patron" ]; then
                mike deploy --push --update-aliases $VERSION_NAME latest
              else
                mike deploy --push $VERSION_NAME
              fi
