name: ci
on:
   push:
      branches:
         - backer
         - patron
         - main
permissions:
   contents: write
jobs:
   deploy:
      runs-on: ubuntu-latest
      steps:
         -  uses: actions/checkout@v3
         -  uses: actions/setup-python@v4
            with:
               python-version: 3.x
         -  uses: actions/cache@v2
            with:
               key: ${{ github.ref }}
               path: .cache
         -  run: pip install mkdocs-material mike mkdocs-roamlinks-plugin mkdocs-rss-plugin

         # Deploy to the 'backer' branch
         -  run: mike deploy backer --branch backer --push --update-aliases backer

         # Deploy to the 'patron' branch
         -  run: mike deploy patron --branch patron --push --update-aliases latest

         # Deploy to the 'main' branch, which for now is the same as 'patron'
         -  run: mike deploy patron --branch main --push --update-aliases latest
